name: Build

on:
  push:
    branches: [main, dev, pre-release]
    tags: ['v*']
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
env:
  LATEST_PY_VERSION: '3.9'

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Cache packages per python version, and reuse until setup.py changes
      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py') }}
          restore-keys: ${{ runner.os }}-pip-${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install '.[dev]'
      - name: Run CLI smoke test
        run: |
          naturtag -cdo 45524803
          naturtag -cdt 48978
      - name: Run unit tests
        run: pytest ./test

  analyze:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.LATEST_PY_VERSION }}

      # Cache packages for latest python version, and reuse until setup.py changes
      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ env.LATEST_PY_VERSION }}-${{ hashFiles('setup.py') }}
          restore-keys: ${{ runner.os }}-pip-${{ env.LATEST_PY_VERSION }}

      - name: Install dependencies
        run: pip install '.[dev]' '.[build]'
      - name: Run style checks
        run: |
          black --check --diff .
          isort --check --diff .
      - name: Run linter
        run: flake8 naturtag
      # TODO
      # - name: Run type checks
      #   run: mypy .
      - name: Generate code coverage report
        run: pytest --cov --cov-report=term --cov-report=html ./test
#      - name: Send code coverage report to Coveralls
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: coveralls
      - name: Test Sphinx documentation build
        run: make -C docs all
      - name: Test package build
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*

  # Deploy pre-release builds from 'pre-release' branch, and stable builds on tags only
  release:
    needs: [test, analyze]
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/pre-release'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.LATEST_PY_VERSION }}

      - name: Set pre-release version number
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo "PRE_RELEASE_SUFFIX=.dev${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          python setup.py --version
      - name: Install dependencies
        run: pip install -U '.[build]'
      - name: Build wheel
        run: |
          python setup.py --version
          python setup.py sdist bdist_wheel
      - name: Deploy to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
