name: Deploy

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      pre-release-suffix:
        description: 'Version suffix for pre-releases ("a", "b", "rc", etc.)'
        required: false
        default: 'dev'
      pre-release-version:
        description: 'Version number for pre-releases; defaults to build number'
        required: false
        default: ''

env:
  LATEST_PY_VERSION: '3.10'


jobs:
  release-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.LATEST_PY_VERSION }}
      - uses: snok/install-poetry@v1.3.1
        with:
          version: 1.2.0a2
          virtualenvs-in-project: true

      - name: Set pre-release version
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        env:
          pre-release-suffix: ${{ github.event.inputs.pre-release-suffix || 'dev' }}
          pre-release-version: ${{ github.event.inputs.pre-release-version || github.run_number }}
        run: |
          poetry version $(poetry version -s).${{ env.pre-release-suffix }}${{ env.pre-release-version }}
          poetry version

      - name: Build and publish to pypi
        run: |
          poetry build
          poetry publish -u  __token__ -p ${{ secrets.PYPI_TOKEN }}

  build-installer:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.LATEST_PY_VERSION }}
      - uses: snok/install-poetry@v1.3.1
        with:
          version: 1.2.0a2
          virtualenvs-in-project: true

      - name: Install system packages
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install -y libegl-dev libxcb1-dev libxcb-image0 libxcb-render0 libwebp-dev libpng16-16

      - name: Cache python packages
        id: cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ env.LATEST_PY_VERSION }}-pyinstaller-${{ matrix.os }}-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          poetry install -v --without dev --extras ui
          poetry run pip install -U pyinstaller setuptools
      - name: Build PyInstaller package
        run: poetry run pyinstaller -y naturtag.spec

      # Include taxon FTS db, compress, and set platform name
      - name: Finish artifact (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          tar -xvzf dist/naturtag/assets/taxon-fts-en.tar.gz --directory dist/naturtag/assets/
          rm dist/naturtag/assets/taxon-fts-en.tar.gz
          tar -C dist/naturtag/ -czvf naturtag.tar.gz .
          echo "DIST_NAME=linux" >> $GITHUB_ENV

      - name: Finish artifact (MacOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          ASSETS=dist/naturtag/Contents/Resources/assets
          tar -xvzf $ASSETS/taxon-fts-en.tar.gz --directory $ASSETS/
          rm $ASSETS/taxon-fts-en.tar.gz
          tar -C dist/naturtag/ -czvf naturtag.tar.gz .
          echo "DIST_NAME=macos" >> $GITHUB_ENV

      - name: Finish artifact (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          tar -xvzf dist\naturtag\assets\taxon-fts-en.tar.gz --directory dist\naturtag\assets\
          Remove-Item dist\naturtag\assets\taxon-fts-en.tar.gz
          tar -C dist\naturtag\ -czvf naturtag.tar.gz .
          echo "DIST_NAME=windows" >> $env:GITHUB_ENV

      - name: Upload workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: naturtag-${{ env.DIST_NAME }}.tar.gz
          path: naturtag.tar.gz

  release-installer:
    runs-on: ubuntu-latest
    needs: build-installer
    steps:
      # Explicitly download each artifact to retain filenames
      - uses: actions/download-artifact@v3
        with:
          name: naturtag-linux.tar.gz
          path: naturtag-linux.tar.gz
      - uses: actions/download-artifact@v3
        with:
          name: naturtag-macos.tar.gz
          path: naturtag-macos.tar.gz
      - uses: actions/download-artifact@v3
        with:
          name: naturtag-windows.tar.gz
          path: naturtag-windows.tar.gz

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: '*tar.gz'
